function GraphSettings(){}

GraphSettings.CANVAS_WIDTH = 1220;
GraphSettings.CANVAS_HEIGHT = 700;

GraphSettings.DEFAULT_MARGIN_H = 75;
GraphSettings.DEFAULT_MARGIN_V = 0;
GraphSettings.DEFAULT_CENTERBONE_SPACER_H = 50;
GraphSettings.DEFAULT_CENTERBONE_SEGMENT_LENGTH = 175;
GraphSettings.DEFAULT_CENTERBONE_VERTEX_WIDTH = 130;
GraphSettings.DEFAULT_CENTERBONE_VERTEX_HEIGHT = 50;
GraphSettings.DEFAULT_SIDEBONE_SPACER_V = 50;
GraphSettings.DEFAULT_SIDEBONE_SEGMENT_LENGTH = 50;
GraphSettings.DEFAULT_SIDEBONE_VERTEX_WIDTH = 150;
GraphSettings.DEFAULT_SIDEBONE_VERTEX_HEIGHT = 35;
GraphSettings.DEFAULT_LATERALBONE_SPACER_H = 50;
GraphSettings.DEFAULT_LATERALBONE_SEGMENT_LENGTH = 70;
GraphSettings.DEFAULT_AUXILLARYBONE_SEGMENT_LENGTH = 25;
GraphSettings.DEFAULT_THETA = 60;

GraphSettings.restoreDefaults = function(){
    GraphSettings.MARGIN_H = GraphSettings.DEFAULT_MARGIN_H;
    GraphSettings.MARGIN_V = GraphSettings.DEFAULT_MARGIN_V;
    GraphSettings.CENTERBONE_SPACER_H = GraphSettings.DEFAULT_CENTERBONE_SPACER_H;
    GraphSettings.CENTERBONE_SEGMENT_LENGTH = GraphSettings.DEFAULT_CENTERBONE_SEGMENT_LENGTH;
    GraphSettings.CENTERBONE_VERTEX_WIDTH = GraphSettings.DEFAULT_CENTERBONE_VERTEX_WIDTH;
    GraphSettings.CENTERBONE_VERTEX_HEIGHT = GraphSettings.DEFAULT_CENTERBONE_VERTEX_HEIGHT;
    GraphSettings.SIDEBONE_SPACER_V = GraphSettings.DEFAULT_SIDEBONE_SPACER_V;
    GraphSettings.SIDEBONE_SEGMENT_LENGTH = GraphSettings.DEFAULT_SIDEBONE_SEGMENT_LENGTH;
    GraphSettings.SIDEBONE_VERTEX_WIDTH = GraphSettings.DEFAULT_SIDEBONE_VERTEX_WIDTH;
    GraphSettings.SIDEBONE_VERTEX_HEIGHT = GraphSettings.DEFAULT_SIDEBONE_VERTEX_HEIGHT;
    GraphSettings.LATERALBONE_SPACER_H = GraphSettings.DEFAULT_LATERALBONE_SPACER_H;
    GraphSettings.LATERALBONE_SEGMENT_LENGTH = GraphSettings.DEFAULT_LATERALBONE_SEGMENT_LENGTH;
    GraphSettings.AUXILLARYBONE_SEGMENT_LENGTH = GraphSettings.DEFAULT_AUXILLARYBONE_SEGMENT_LENGTH;
    GraphSettings.THETA = GraphSettings.DEFAULT_THETA;
};
